language: java
jdk:
 - openjdk11

sudo: required
dist: xenial

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "miageskillz"

matrix:
  include:
    - language: java
      jdk: openjdk11
      script:
        - ./gradlew clean build
    - language: node_js
      node_js: stable
      services:
        - docker
        - xvfb
      addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable

      before_script:
        - npm install
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - cd ./src/main/java/miage/skillz/frontend/
      script:
        - npm run build --prod --browsers=ChromeHeadlessNoSandbox
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker build -t skillz-front .;
          docker tag skillz-front lethuydung0109/skillz-front;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
          docker push lethuydung0109/skillz-front;
          fi