language: java
jdk:
  - openjdk11
addons:
  sonarqube:
    - organization: "miageskillz" # the key of the org you chose at step #3
    - token:
        secure: 916dcc70d496e1150df3fdae8751b758cdcd64df

script:
  - ./gradlew clean build
  - sonar-scanner
notifications:
  email: lethuydung0109@gmail.com

#dist: xenial

#script:
#  # other script steps might be done before running the actual analysis
