language: java
jdk:
 - openjdk11
# addons:
#   sonarqube:
#     - organization: "miageskillz" # the key of the org you chose at step #3
#     - token:
#         secure: 916dcc70d496e1150df3fdae8751b758cdcd64df

sudo: required
dist: xenial

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - language: java
      jdk: openjdk11
      jobs:
        include:
          - stage: build java
            script:
              - ./gradlew clean build
          - stage: build docker image
            script:
              - echo "Build docker image"

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./src/main/java/miage/skillz/frontend/
      jobs:
        include:
          - stage: build npm
            script:
              - npm run build --prod --browsers=ChromeHeadlessNoSandbox
          - stage: Build docker image
            script:
              - echo "Build docker image npm"

#Ajout le 30/04 : Codecov + jacocoTestReport
    - language: java
        jdk: openjdk11
        before_script:
          - chmod +x gradlew
        script:
          - ./gradlew check jacocoTestReport coveralls sendCoverageToCodacy
          - ./gradlew codeCoverageReport
        after_success:
          - bash <(curl -s https://codecov.io/bash)
        test:
          post:
            - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
            - bash <(curl -s https://codecov.io/bash)