language: java
addons:
  sonarcloud:
    organization: skillz
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  - "./gradlew check jacocoTestReport coveralls sendCoverageToCodacy"

before_deploy:
  - export VERSION=`./gradlew -q version`
  - export BINDIR="build/libs"
  - export BINFILE="skillz-${VERSION}"
  - export DOCDIR="build/docs/asciidocPdf"
  - export DOCFILE="main"
  - mv "${DOCDIR}/${DOCFILE}.pdf" "${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
  - export BINARY="${BINDIR}/${BINFILE}.jar"
  - export DOCUMENTATION="${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
  - echo binary is ${BINARY}
  - echo documentation is ${DOCUMENTATION}
  - |
    if [ $TRAVIS_BRANCH = "develop" ]
    then
      export TRAVIS_TAG=v${VERSION}-SNAPSHOT
    else
      export TRAVIS_TAG=v${VERSION}
    fi
  - |
    if [ $TRAVIS_BRANCH = "develop" ]
    then
      git tag ${TRAVIS_TAG}
      echo tag ${TRAVIS_TAG}
    else
      echo no tag
    fi
deploy:
  - provider: releases
    file:
      - ${BINARY}
      - ${DOCUMENTATION}
    skip_cleanup: true
    overwrite: true
    draft: false
    on:
      #branch master
      tags: true
      all_branches: true
    name: $TRAVIS_TAG
  - provider: releases
    file:
      - ${BINARY}
      - ${DOCUMENTATION}
    skip_cleanup: true
    overwrite: true
    draft: true
    on:
      branch: develop
      tags: false
    name: $TRAVIS_TAG

cache:
  directories:
    - "$HOME/.sonar/cache"